name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: cheat-engine/cheat-engine
        ref: '7.5'

    - uses: gcarreno/setup-lazarus@v3.2.15
      with:
        lazarus-version: "2.2.2"

    - uses: microsoft/setup-msbuild@v2

    - name: Install i386 cross-compiler
      shell: pwsh
      run: |
        $lazdir = Split-Path (Get-Command lazbuild).Source
        curl.exe -L "https://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2064%20bits/Lazarus%202.2.2/lazarus-2.2.2-fpc-3.2.2-cross-i386-win32-win64.exe/download" -o cross-compiler.exe
        .\cross-compiler.exe /verysilent /DIR="$lazdir"

#     - run: |
#         if (-not (Test-Path lazarus-2.2.0-fpc-3.2.2-win64.exe)) {
#             curl.exe -LO https://udomain.dl.sourceforge.net/project/lazarus/Lazarus%20Windows%2064%20bits/Lazarus%202.2.0/lazarus-2.2.0-fpc-3.2.2-win64.exe
#         }
#         ./lazarus-2.2.0-fpc-3.2.2-win64.exe /verysilent

    - run: lazbuild -B "Cheat Engine/cheatengine.lpi" --cpu=x86_64 --build-mode="Release 64-Bit O4 AVX2"

#     - run: ls -r '*.lpi' | % { lazbuild -B $_ --cpu=x86_64 --build-mode="Release 64-Bit O4 AVX2" }

    - run: lazbuild -B "Cheat Engine/speedhack/speedhack.lpi" --cpu=x86_64 --build-mode="64-bit"

    - run: lazbuild -B "Cheat Engine/luaclient/luaclient.lpi" --cpu=x86_64 --build-mode="Release 64"

    - run: lazbuild -B "Cheat Engine/VEHDebug/vehdebug.lpi" --cpu=x86_64 --build-mode="release 64"

    - run: lazbuild -B "Cheat Engine/speedhack/speedhack.lpi" --cpu=i386 --build-mode="32-bit"
      continue-on-error: true

    - run: lazbuild -B "Cheat Engine/luaclient/luaclient.lpi" --cpu=i386 --build-mode="Release 32"
      continue-on-error: true

    - run: lazbuild -B "Cheat Engine/VEHDebug/vehdebug.lpi" --cpu=i386 --build-mode="release 32"
      continue-on-error: true

    - run: msbuild "Cheat Engine/Direct x mess/Direct x mess.sln" /p:Configuration=Release /p:Platform=Win32
    - run: msbuild "Cheat Engine/Direct x mess/Direct x mess.sln" /p:Configuration=Release /p:Platform=x64

    - run: msbuild "Cheat Engine/MonoDataCollector/MonoDataCollector.sln" /p:Configuration=Release /p:Platform=Win32
    - run: msbuild "Cheat Engine/MonoDataCollector/MonoDataCollector.sln" /p:Configuration=Release /p:Platform=x64

    - run: msbuild "Cheat Engine/DotNetDataCollector/DotNetDataCollector.sln" /p:Configuration=Release /p:Platform=Win32
    - run: msbuild "Cheat Engine/DotNetDataCollector/DotNetDataCollector.sln" /p:Configuration=Release /p:Platform=x64

    - run: msbuild "Cheat Engine/Java/CEJVMTI/CEJVMTI.sln" /p:Configuration=Release /p:Platform=Win32
    - run: msbuild "Cheat Engine/Java/CEJVMTI/CEJVMTI.sln" /p:Configuration=Release /p:Platform=x64

    - run: msbuild "Cheat Engine/DotNetCompiler/CSCompiler/CSCompiler.sln" /p:Configuration=Release

    - run: msbuild "Cheat Engine/DotNetInvasiveDataCollector/DotNetInvasiveDataCollector.sln" /p:Configuration=Release

    - run: msbuild "Cheat Engine/tcclib/win32/tcc/tcc.sln" /p:Configuration="Output to 32 (Release)" /p:Platform=Win32
    - run: msbuild "Cheat Engine/tcclib/win32/tcc/tcc.sln" /p:Configuration="Output to 32 (Release)" /p:Platform=x64
    - run: msbuild "Cheat Engine/tcclib/win32/tcc/tcc.sln" /p:Configuration="Output to 64 (Release)" /p:Platform=Win32
    - run: msbuild "Cheat Engine/tcclib/win32/tcc/tcc.sln" /p:Configuration="Output to 64 (Release)" /p:Platform=x64

    - run: 7z a CE.7z ".\Cheat Engine\bin\*"

    - uses: actions/upload-artifact@master
      with:
        path: CE.7z
        name: CE.7z
